server:
  type: default
  applicationConnectors:
    - type: http
      port: 8443
  adminConnectors:
    - type: http
      port: 8444
swagger:
  resourcePackage: com.example.helloworld.resources

template: Hello, %s!
defaultName: Stranger

